name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH Key
      shell: bash
      run: |
        echo "${{ secrets.EC2_KEY }}" > ~/my-test-key.pem
        chmod 400 ~/my-test-key.pem

    - name: Deploy Code
      shell: bash
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          cd /cico-test
          git pull origin main
          docker compose down
          docker compose up -d --build
          docker compose exec -T web python manage.py migrate
          docker compose exec -T web python manage.py collectstatic --noinput
        EOF
